[images]
  remote_images = [
    "https://ext.same-assets.com/**"
  ]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@netlify/plugin-nextjs"]
